---
# Variables comunes para el clúster Kubernetes
kube_version: "1.31.0"
container_runtime: "containerd"
runtime: "containerd"
containerd_version: "1.7.15"
cilium_version: "1.15.5"
pod_network_cidr: "10.244.0.0/16"
