calico_operator_manifest_url: https://raw.githubusercontent.com/projectcalico/calico/v3.31.1/manifests/tigera-operator.yaml
calico_custom_resources_path: "{{ playbook_dir }}/config/custom-resources.yaml"
calico_operator_apply_wait: 10
calico_node_ready_retries: 120
calico_node_ready_delay: 2
