---
k8s_uninstall_kubeconfig_path: /etc/kubernetes/admin.conf
k8s_uninstall_reset_cri_socket: unix:///run/containerd/containerd.sock
k8s_uninstall_clean_directories:
  - /etc/kubernetes
  - /etc/kubernetes/pki
  - /etc/kubernetes/manifests
  - /etc/cni/net.d
  - /var/lib/etcd
  - /var/lib/cni
  - /var/lib/kubelet
  - /var/tmp/etcd
  - /var/lib/kubeadm
  - /var/lib/containerd/io.containerd.snapshotter.v1.overlayfs
  - /var/lib/containerd
  - /run/kubernetes
k8s_uninstall_clean_files:
  - "{{ k8s_uninstall_kubeconfig_path }}"
k8s_uninstall_remove_packages: true
k8s_uninstall_packages_to_remove:
  - kubelet
  - kubeadm
  - kubectl
k8s_uninstall_remove_container_runtime: true
k8s_uninstall_container_runtime_packages:
  - containerd.io
k8s_uninstall_remove_repos: true
k8s_uninstall_kubernetes_repo_file: /etc/apt/sources.list.d/kubernetes.list
k8s_uninstall_containerd_repo_file: /etc/apt/sources.list.d/docker-ce.list
k8s_uninstall_kubernetes_keyring_path: "{{ kubernetes_keyring_path | default('/etc/apt/keyrings/kubernetes-apt-keyring.gpg') }}"
k8s_uninstall_containerd_keyring_path: "{{ containerd_keyring_path | default('/etc/apt/keyrings/docker-archive-keyring.gpg') }}"
