[kube_control_plane]
cp1 ansible_host=10.0.0.10 ansible_port=22 ansible_connection=ssh

[kube_node]
worker1 ansible_host=10.0.0.11 ansible_port=22 ansible_connection=ssh
worker2 ansible_host=10.0.0.12 ansible_port=22 ansible_connection=ssh

[all:vars]
# Establece ansible_user y otras opciones sensibles en un vault o en hosts_vars
ansible_python_interpreter=/usr/bin/python3
