# Populate this file with the details of the local node used for single-node deployments.
# Values here can be overridden via CLI flags when invoking ./single-node_deploy.
HOST_IP=192.168.123.164
HOST_NAME=vm1
